spring.application.name=spring-ecommerce
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:database
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
security.jwt.token.secret-key=your-very-secret-key-super-super-long-special-key
security.jwt.token.expire-length=3600000

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create
logging.level.org.hibernate.orm.jdbc.bind=TRACE


